### ISSUE TITLE
Fails to register in Python 2.7 on Windows

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/pytest-nunit#2]
```
==============================================================================
Generating script.
Script contents:
pytest tests -v -m "not testfail" --nunitxml=nunit\test-results.xml --test-run-title="Test Custom Title"
========================== Starting Command Output ===========================
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\aa09e35c-5850-4ae6-9f6e-7b2823b54942.cmd""
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\hostedtoolcache\windows\Python\2.7.14\x64\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\_pytest\config\__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\_pytest\config\__init__.py", line 207, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\_pytest\helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\_pytest\config\__init__.py", line 687, in pytest_cmdline_parse
    self.parse(args)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\_pytest\config\__init__.py", line 895, in parse
    self._preparse(args, addopts=addopts)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\_pytest\config\__init__.py", line 841, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\pluggy\manager.py", line 292, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\importlib_metadata\__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named pytest_nunit.plugin
```

**Comment by asottile** [comment]
reopening since I'm pretty sure this doesn't fix the setuptools issue

**Comment by tonybaloney** [comment]
Think it autoclosed

**Comment by tonybaloney** [comment]
Need to fix #4 first

**Comment by tonybaloney** [comment]
Only 1 issue now remaining https://dev.azure.com/AnthonyShaw/pytest-nunit/_build/results?buildId=413

**Comment by asottile** [comment]
I *think* that just needs a newer version of setuptools at install time

**Comment by tonybaloney** [comment]
Verified the 2.7 issue is fixed. 3.4 is still broken as per #1
